version: "3.7"
services:

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MYSQL_ONETIME_PASSWORD=yes
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - 3306

  shiny:
    build:
      context: .
      dockerfile: docker/shiny/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    ports:
      - '${APP_PORT}:3838'
    volumes:
      - './docker/shiny/logs:/var/log/shiny-server'
      - './app:/srv/shiny-server'
    depends_on:
      - db